# Generated by Django 4.0 on 2022-07-05 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='Client',
        ),
    ]
