# Generated by Django 4.0 on 2022-07-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(choices=[(0, 'common_user'), (1, 'admin')], default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
