# Generated by Django 4.0 on 2022-07-06 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('client_api', '0002_alter_client_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='client',
            table=None,
        ),
    ]
