# Generated by Django 4.0 on 2022-07-06 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_api', '0003_remove_client_name_client_user_alter_client_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='client',
        ),
    ]
