# Generated by Django 4.0 on 2022-07-05 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialist_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='workerservice',
            table='worker_service',
        ),
    ]
