# Generated by Django 4.0 on 2022-07-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_api', '0001_initial'),
        ('specialist_api', '0002_alter_workerservice_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='appointments',
            field=models.ManyToManyField(through='specialist_api.Appointment', to='client_api.Client'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='services',
            field=models.ManyToManyField(through='specialist_api.WorkerService', to='specialist_api.Service'),
        ),
    ]
