# Generated by Django 4.0 on 2022-07-05 21:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('specialist_api', '0003_worker_appointments_alter_worker_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2022, 7, 5, 21, 20, 49, 493579, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
