# Generated by Django 4.0 on 2022-07-09 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_api', '0003_alter_customuser_is_superuser'),
        ('specialist_api', '0003_alter_worker_appointments_alter_worker_services_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='work_schedule',
        ),
        migrations.AlterField(
            model_name='worker',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to='client_api.customuser'),
        ),
    ]
