# Generated by Django 4.0 on 2022-07-09 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialist_api', '0004_remove_worker_work_schedule_alter_worker_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='appointments',
        ),
    ]
