# Generated by Django 4.0 on 2022-07-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_api', '0002_alter_client_table'),
        ('specialist_api', '0004_alter_schedule_end_time_alter_schedule_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='appointments',
            field=models.ManyToManyField(blank=True, null=True, through='specialist_api.Appointment', to='client_api.Client'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, through='specialist_api.WorkerService', to='specialist_api.Service'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='work_schedule',
            field=models.ManyToManyField(blank=True, null=True, through='specialist_api.Schedule', to='specialist_api.Location'),
        ),
    ]
