# Generated by Django 4.0 on 2022-07-09 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist_api', '0005_remove_worker_appointments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='_seconds_length',
        ),
        migrations.AddField(
            model_name='service',
            name='length',
            field=models.TimeField(default=datetime.datetime(2022, 7, 9, 14, 55, 7, 166227)),
            preserve_default=False,
        ),
    ]
