# Generated by Django 4.0 on 2022-07-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_api', '0002_alter_client_table'),
        ('specialist_api', '0005_alter_worker_appointments_alter_worker_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='appointments',
            field=models.ManyToManyField(through='specialist_api.Appointment', to='client_api.Client'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='services',
            field=models.ManyToManyField(through='specialist_api.WorkerService', to='specialist_api.Service'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='work_schedule',
            field=models.ManyToManyField(through='specialist_api.Schedule', to='specialist_api.Location'),
        ),
    ]
