# Generated by Django 4.0 on 2022-07-05 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialist_api', '0006_alter_worker_appointments_alter_worker_services_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='seconds_length',
            new_name='_seconds_length',
        ),
    ]
