# Generated by Django 4.0 on 2022-07-09 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist_api', '0007_remove_service_length_service__seconds_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='_seconds_length',
        ),
        migrations.AddField(
            model_name='service',
            name='length',
            field=models.DurationField(default=datetime.timedelta(seconds=1200)),
            preserve_default=False,
        ),
    ]
