# Generated by Django 4.0 on 2022-07-05 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialist_api', '0007_rename_seconds_length_service__seconds_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='end_time',
            new_name='_end_time',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='start_time',
            new_name='_start_time',
        ),
    ]
