# Generated by Django 4.0 on 2022-07-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist_api', '0008_rename_end_time_schedule__end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='_end_time',
            field=models.TimeField(verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='_start_time',
            field=models.TimeField(verbose_name='start time'),
        ),
    ]
