# Generated by Django 4.0 on 2022-07-06 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('specialist_api', '0009_alter_schedule__end_time_alter_schedule__start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='name',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='surname',
        ),
        migrations.AddField(
            model_name='worker',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='worker', to='auth.user'),
            preserve_default=False,
        ),
    ]
