# Generated by Django 4.0 on 2022-07-10 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialist_api', '0009_worker_appointments_worker_schedules'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-scheduled_for']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['city']},
        ),
    ]
