# Generated by Django 4.0 on 2022-07-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist_api', '0010_alter_appointment_options_alter_location_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
