# Generated by Django 4.0 on 2022-07-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist_api', '0010_remove_worker_name_remove_worker_surname_worker_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='_seconds_length',
            field=models.FloatField(verbose_name='length'),
        ),
    ]
