# Generated by Django 4.0 on 2022-07-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist_api', '0011_alter_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='schedules',
            field=models.ManyToManyField(blank=True, related_name='worker_schedule', through='specialist_api.Schedule', to='specialist_api.Location'),
        ),
    ]
