# Generated by Django 4.0 on 2022-07-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist_api', '0012_alter_worker_schedules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='schedules',
            field=models.ManyToManyField(blank=True, through='specialist_api.Schedule', to='specialist_api.Location'),
        ),
    ]
