# Generated by Django 4.0 on 2022-07-11 17:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client_api', '0003_alter_customuser_is_superuser'),
        ('specialist_api', '0013_alter_worker_schedules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='appointments',
            field=models.ManyToManyField(blank=True, related_name='+', through='specialist_api.Appointment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='worker',
            name='schedules',
            field=models.ManyToManyField(blank=True, related_name='+', through='specialist_api.Schedule', to='specialist_api.Location'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='+', through='specialist_api.WorkerService', to='specialist_api.Service'),
        ),
    ]
