# Generated by Django 4.0 on 2022-07-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist_api', '0017_rename_proffesion_worker_proffession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='_end_time',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='_start_time',
            new_name='start_time',
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day_of_week',
            field=models.SmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], db_index=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
