# Generated by Django 4.0 on 2022-07-15 02:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist_api', '0018_rename__end_time_schedule_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='length',
        ),
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.TimeField(default=datetime.time(2, 17, 12, 531)),
            preserve_default=False,
        ),
    ]
