# Generated by Django 4.0 on 2022-07-15 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialist_api', '0018_alter_location_city_alter_schedule_day_of_week_and_more'),
        ('specialist_api', '0019_remove_service_length_service_duration'),
    ]

    operations = [
    ]
