# Generated by Django 4.0 on 2022-07-15 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist_api', '0020_merge_20220715_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.DurationField(),
        ),
    ]
